### PR TITLE
allow users to get the status text of the reponse when uploading

### PR DESCRIPTION
**Pull request by vincentrussell**
I need this to be able to display error messages when the upload fails

### CODE REVIEW

**Comment by danialfarid** [comment]
angular $http success and error doesn't return statusText in the parameters and this plugin should follow the same pattern.

**Comment by lookfirst** [comment]
["On failure, the promise is resolved with the http response object, without the resource property."](https://docs.angularjs.org/api/ngResource/service/$resource)

`$resource` does the *smart* thing and just gives back the entire http response object. I suspect that since `$resource` probably came after `$http`, that that is the intended direction of the authors. I'd be curious to find out the thought pattern on that.

In fact, it looks like this [has annoyed a lot of other people as well](https://github.com/angular/angular.js/issues/2335).

Please choose to be on the right side of history on this issue. :smile:

**Comment by vincentrussell** [comment]
I didn't realize that I could use catch instead of error with ng-file-upload.  That actually services my use case just fine.

Thanks,

**Comment by danialfarid** [comment]
You can use `then`, `catch` if you need the whole response object.

**Pull request closed without merging**
