### PR TITLE
Add ngf-allow-dir to ngf-select as well.

### PR DESCRIPTION
**Pull request by alinVD**
Hi Danial,

I made a small change to allow ngf-allow-dir behavior on ngf-select as well. When set, the "webkitdirectory" and "directory" attributes are added to the input element to allow "upload dir" behavior on Chrome. This does not affect other browsers.

I would appreciate if you accept the pull request (after review).

Alin

### CODE REVIEW

**Comment by danialfarid** [comment]
Thanks for the pull request. I would change the name `ngfAllowDir` to `ngfDirectory` to be able to use just `directory` property for input type file. So that would need to be changed in the drop code too.

**Comment by alinVD** [comment]
I switched the ngf-allow-dir to ngf-directory when used in ngf-select. Changing it in ngf-drop would break existing code. 

Alin

**Comment by alinVD** [comment]
Danial,

If you are happy with my changes, can you please merge my branch.

Thanks,
Alin

**Comment by danialfarid** [comment]
I have ported most of the code into TypeScript for angular2 and gonna have a back port version of it for angular 1 so the whole code structure will change. So most probably next version gonna replace most of this code. If there are more delay in pushing the new angular2 version then I will have another version of this code and gonna merge this. You can try to send a pull request for ng2 branch where the typescript code is instead of master. Also when you do pull request just commit the changes that are actual logic changes, There are many changes in the index.html file. Also you have updated the docs to have ng-directory for both drop and select but the drop source code has not changed.
I will try to bring this logic to ng2 branch if you don't send a pull request for the next versions.

**Comment by alinVD** [comment]
Hi Danial,

My code changes are small and follow what you already had in place. If you do not happen to port my changes during the TS rewrite, I will happily do so. 

Thanks,
Alin

**Pull request closed without merging**
