### PR TITLE
Explained the usage of fileFormDataName in upload function

### PR DESCRIPTION
**Pull request by roydondsouza**
Added ```fileFormDataName ``` to explain usage
```javascript
 Upload.upload({
   url: 'upload/url',
   fields: {'username': $scope.username},
//---
   fileFormDataName : 'fileDataName', //by default the field name is 'file' *Optional 
//---
   file: file
})
```
We can have a custom form data name for the file content. There is no proper documentation, this might be helpful for many.

### CODE REVIEW

**Comment by danialfarid** [comment]
It is explained in the full doc section. That section is just a sample and most people wont need that option to be set.

**Comment by roydondsouza** [comment]
Sure, no problem. Can you point me there?  I couldn't find the documentation.

**Comment by roydondsouza** [comment]
@danialfarid If i want to get overall file progress how can I get it?
Eg: 
Say I drag 3 files.
I get progress separately. I want total filesize of all 3 files, which I can calculate from model.
How can I get total loaded progress from all 3 file? 
So I can get total percentage of all 3 uploads and show 1 mb of 9mb
Have anything in build?

**Comment by danialfarid** [comment]
@roydondsouza just calculate the percentage from all files loaded and total. I remember I wrote something similar in one of the issues if you search for it.

**Comment by roydondsouza** [comment]
Thank you very much.
I thought that was an inbuilt feature so I asked. I have done the
calculations. Thank you.

Regards,

Roydon D' Souza
Ph.: +91-9739791096

Disclaimer Notice: This message contains confidential information and is
intended only for the individual named. If you are not the named addressee
you should not disseminate, distribute or copy this e-mail. Please notify
the sender immediately by e-mail if you have received this e-mail by
mistake and delete this e-mail from your system. E-mail transmission cannot
be guaranteed to be secure or error-free as information could be
intercepted, corrupted, lost, destroyed, arrive late or incomplete, or
contain viruses. The sender therefore does not accept liability for any
errors or omissions in the contents of this message, which arise as a
result of e-mail transmission. If verification is required please request a
hard-copy version.

WARNING: Computer viruses can be transmitted via email. The recipient
should check this email and any attachments for the presence of viruses.
The company accepts no liability for any damage caused by any virus
transmitted by this email. E-mail transmission cannot be guaranteed to be
secure or error-free as information could be intercepted, corrupted, lost,
destroyed, arrive late or incomplete, or contain viruses. The sender
therefore does not accept liability for any errors or omissions in the
contents of this message, which arise as a result of e-mail transmission.

All Emails of Roydon D'Souza are managed by the MailBox.
http://www.roydondsouza.com

**Pull request closed without merging**
