### PR TITLE
Fixes problem with ngf-drag-over-class caused by dragleave event on child-node

### PR DESCRIPTION
**Pull request by HannesHentzschel**
I fixed a problem that occurs when child-elements are present inside an element using the ngf-drag-over-class. When the dragleave event fires on a child node the drag-over-class was removed.

Solution based on this stackoverflow response:
http://stackoverflow.com/questions/7110353/html5-dragleave-fired-when-hovering-a-child-element

### CODE REVIEW

**Comment by danialfarid** [comment]
Could you elaborate more on the issue? A reproducible example?
Also could you submit your PR without running grunt just with the changes in the src folder to avoid conflicts.

**Comment by HannesHentzschel** [comment]
Hi,

here is an example: http://jsfiddle.net/zm2vqyrt/1/
Try to hover a file over the form. A red border around the form, as defined by the ngf-drag-over-class should appear. Now move the mouse around while still hovering the file over the the form. You should see that the border disappears and appears again. This is caused from the dragenter / dragleave events on the child elements of the form.

Having child elements in an ngf-drop element can be pretty useful. I use it to allow users to add attachments to a text by simply dropping files on a contenteditable element. Just like gmail does it while composing an email.

PS: it seems that the issue is much more visible in Chrome than in Firefox. Firefox only shows it while hovering over the submit button.

I will create a new PR without running grunt.

**Comment by danialfarid** [comment]
It always stays red for me. Which browser version are you testing on?

**Comment by HannesHentzschel** [comment]
I am testing in Chromium Version 51.0.2704.79.
It should also happen in Chrome.

Here is a demo-video:
https://drive.google.com/file/d/0B0Mqg8-KXRFyYm1QMG9EUlFYZ0E/view?usp=sharing

**Comment by danialfarid** [comment]
It could be a Chromium bug. Try it on Chrome. What OS are you using? https://drive.google.com/file/d/0B-ltsmYI_HLxZ1JFcl9XR05JOTQ/view?usp=sharing

**Comment by HannesHentzschel** [comment]
Thanks for providing the video.

I use Ubuntu.
Now I also tested it using Chrome on Windows 7 and there the error is also present.
I tested it on Mac using Chrome too, and there the error does not happen. Very strange.

It seems to be a webkit bug, which is also discussed in the stackoverflow comments on this issues:
http://stackoverflow.com/questions/7110353/html5-dragleave-fired-when-hovering-a-child-element#comment13662949_7110353
The webkit bug seems to exist since 5 years. Probably wont be solved soon.

**Comment by danialfarid** [comment]
try bumping up dragOverDelay that's for that purpose. There was a similar issue before and that was for the fix.

**Comment by HannesHentzschel** [comment]
Thanks ... that also solves the issue.
I will continue to use my solution.

**Pull request closed without merging**
