### PR TITLE
Provider for setting directive defaults (#869)

### PR DESCRIPTION
**Pull request by HHogg**
I think I've done my best to check all the possible directive configurations in different combinations to make sure everything still works and the defaults can be overridden. 

I started off by splitting the defaults for the select and drop directives but there was soon an overlap for configuring the validation attributes which are shared between the two... so I've just gone for one default object.

For Issue: https://github.com/danialfarid/ng-file-upload/issues/869

API:
```js
angular.module('myApp', [
  'ngFileUpload'
])

.config(function(UploadProvider) {
  UploadProvider.setDefaults({
    accept: String, // Default: null
    allowDir: Boolean, // Default: false
    capture: String, // Default: null
    disabled: Boolean, // Default: false
    dragOverClass: String || Object || Function, // Default: 'dragover'
    dragOverDelay: Number, // Default: 1
    hideOnDropNotAvailable: Boolean // Default: false
    keep: Boolean, // Default: false
    keepDistinct: Boolean, // Default: false
    maxFileSize: Number, // Default: 9007199254740991
    minFileSize: Number, // Default: -1
    multiple: Boolean, // Default: false
    ngfAccept: String || Function, // Default: null
    resetOnClick: Boolean, // Default: true
    resetOnModelClick: Boolean, // Default: true
    src: String, // Default: ''
    stopPropagation: Boolean, // Default: false
  });
});

### CODE REVIEW

**Comment by HHogg** [comment]
@danialfarid just a couple of questions: 

* It's not documented but looking into the code it looks like [ngf-change can be substituted with ngf-drop](https://github.com/danialfarid/ng-file-upload/blob/master/src/drop.js#L100). Does the readme need updating to show this? 

* What's the purpose of matching `/\W+$files\W+/` with in `ngf-drop` and `ngf-select`? [Here](https://github.com/danialfarid/ng-file-upload/blob/master/src/drop.js#L54) and [here](https://github.com/danialfarid/ng-file-upload/blob/master/src/select.js#L37)... I can't work out what it is supposed to match, and the documentation says the only valid inputs are `true` or `false`?

**Comment by danialfarid** [comment]
The PR had too many changes in the source code to keep track of,
I have added the feature to version 5.1.0 focusing on  minimal changes.

Thanks for submitting the PR

**Comment by HHogg** [comment]
@danialfarid I can resubmit without the indentation corrections, if that will make it clearer to see the changes in logic?

**Comment by danialfarid** [comment]
The thing is that there were so many changes that I couldn't track if any of those would break any existing functionality. So the way I implemented it I just replace anywhere that in the existing code we have attr.direciveName with a function call getAttr(attr, directiveName) and in that function I would check the default value if any exists. Also there was no need for an initial default values. Anyway it's already implemented, if you have any suggestion or improvements let me know.

**Pull request closed without merging**
