### PR TITLE
Asp.Net Web Api Demo 

### PR DESCRIPTION
**Pull request by stewartm83**
Demo showing how to use ng-file-upload with Asp.Net Web Api.
Server code provided by Jay Chase.

https://code.msdn.microsoft.com/AngularJS-with-Web-API-22f62a6e

### CODE REVIEW

**Comment by stewartm83** [comment]
View deployed sample on 
http://angular-file-upload.azurewebsites.net/

Still need to be polished.

**Comment by danialfarid** [comment]
This is best to be as a separate github since there are a lot of code and you are using unrelated libraries like bootstrap jquery modernizer. 
If you make a separate github I will link it in the README file or a wiki page to your repository for ASP.Net sample.

**Comment by stewartm83** [comment]
Okay understood. I will create a new repo for it and share the link.

Thanks

**Comment by stewartm83** [comment]
Have created the repo and it can be found on

https://github.com/stewartm83/angular-fileupload-sample

Thanks

**Comment by danialfarid** [comment]
Thanks, Do you wanna add "Server code provided by Jay Chase.
https://code.msdn.microsoft.com/AngularJS-with-Web-API-22f62a6e"
to your readme file?

**Comment by danialfarid** [comment]
Added to the docs.

**Comment by stewartm83** [comment]
Added reference to Jay Chase's code to the docs.

**Pull request closed without merging**
