### PR TITLE
Support data as an array to guarantee order

### PR DESCRIPTION
**Pull request by dtjohnson**
I ran into an issue where I needed a text field to be send in the FormData _before_ the files. The current data is added by enumerating the properties in the data object. While this works if you add the properties to the object in the order you want emitted, the JS spec says the enumeration of the properties is not guaranteed.

This pull request adds an array form of data that guarantees the order. The array contains objects with 'name' and 'value' properties.

### CODE REVIEW

**Comment by danialfarid** [comment]
The order of the form data should not be matter. It is probably a server bug.
Anyway you can workaround it with formDataAppender option in this rare case and special convention for this rare case would not be necessary imo.

**Comment by dtjohnson** [comment]
The order of the form data does indeed matter if the server expects to receive them in a particular order. For simple file uploads that's typically not a concern but for more advanced use cases it definitely matters--particularly if you are using text fields.

The order of iteration of an object as you are doing is not guaranteed. See here:
http://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order

There doesn't seem to be any documentation on the "formDataAppender" option you mentioned...

**Comment by danialfarid** [comment]
Could you submit your PR without running grunt and just the changes in the src folder?

**Comment by danialfarid** [comment]
There has been changes to that file so you might as well submit a new PR with just the necessary changes to the src files.

**Pull request closed without merging**
