### PR TITLE
Fix sending formdata arrays 

### PR DESCRIPTION
**Pull request by ValentinPirgach**

### CODE REVIEW

**Comment by danialfarid** [comment]
What this fix is for? What issue?

**Comment by danialfarid** [comment]
Pull requests generally need to be linked to an issue.

**Comment by ValentinPirgach** [comment]
When I send an array to the Rails server he takes an array as an associative array, instead of real array ("0" => "some value", etc.). So I just added one check to detect an array and added '[]' to the end of formdata key.

**Comment by danialfarid** [comment]
You can use arrayKey option for that.

**Pull request closed without merging**
