### PR TITLE
Fix #837 ngf-select not opening using Chrome on Windows

### LINKED ISSUE #837: ngf-select not opening window to select file
Team,

I am working on file upload once user selects a file from Window. 
I have encountered an issue on click on upload button, the Window to select file is not opening.

Did some googling and find one article https://github.com/danialfarid/ng-file-upload/issues/813

My input file is here and all the file upload input tags are inside of a ng-repeat.
"input type="file" ngf-select ngf-change="myUpload($files, $index)" />"

I have seen setTimeout function calls clickAndAssign(evt) method. And clickAndAssign(evt) method is defined inside another method namely clickHandler(evt). Also, both the methods have same argument name which is redundant.

That is the reason, file upload Window is not opening.

I have fixed the same.

   function clickAndAssign(event) {
                if (event) {
                    fileElem[0].click();
                }
               // if (isInputTypeFile() || !evt) {
               //     elem.bind('click touchend', clickHandler);
               //}
            }

Kindly review and let me know your advise.

### PR DESCRIPTION
**Pull request by pangwa**
Using the fix suggested by @DavidAtTrigger which use the correct
regex to check whether UA is Safari on Windows.

Tested using Chrome on windows.

### CODE REVIEW

**Comment by danialfarid** [comment]
There is a check `ua.indexOf('Chrome') === -1` right before the expression so the Chrome check in the regexp doesn't seem to be necessary.

**Comment by danialfarid** [comment]
Could you post the link you are referring to for the correct syntax.

**Comment by pangwa** [comment]
https://github.com/danialfarid/ng-file-upload/issues/837

There is a comment by DavidAtTrigger suggesting the fix.
 Search below text willl find the comment:
"DavidAtTrigger commented on 28 Jul 2015"

**Comment by danialfarid** [comment]
So what the issue is exactly?

**Comment by pangwa** [comment]
The issue is:
Single click will not open the select files dialog using Chrome on Windows.

**Comment by danialfarid** [comment]
What windows?

**Comment by danialfarid** [comment]
Just tested the demo page on windows 7 chrome and it is working fine.

**Comment by pangwa** [comment]
You may need to try several times to trigger this issue. I reproduced this issue after clicking on the link 3 times.

**Comment by danialfarid** [comment]
Works every time with a single click.
You gotta provide steps to reproduce if you think this is a bug.

**Comment by jackanderson** [comment]
was anyone ever going to merge this request?!

**Comment by samrose3** [comment]
I am still having this issue. Any other fixes to this?

**Comment by pangwa** [comment]
I guess this is not needed anymore.

**Pull request closed without merging**
