### PR TITLE
Fix date form field serialization (#649)

### PR DESCRIPTION
**Pull request by marshall007**
See #649 for example.

### CODE REVIEW

**Comment by rdennis** [comment]
+1 Having to convert dates to strings before posting is annoying.

**Comment by danialfarid** [comment]
Which line fixes the problem?

**Comment by rdennis** [comment]
I am obviously not the author, but it looks like line `146` is the meat of the fix.

**Comment by marshall007** [comment]
Sorry for the delay, @rdennis is correct. The rest of the changes are just cleanup with no changes to existing behavior.

**Pull request merged**
