### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by drakmail**
Fix issue with Upload on file change example in first examples block.

### CODE REVIEW

**Comment by danialfarid** [comment]
This is not an issue, it would work without having an ng-model.

**Comment by drakmail** [comment]
It doesn't work for me =/

**Comment by danialfarid** [comment]
What doesn't work?

**Comment by danialfarid** [comment]
Can you create a jsfiddle? the jsfiddle sample on readme file has exactly an example like that.

**Pull request closed without merging**
